### ISSUE TITLE
RV 10.82.6 Griffith

### ISSUE THREAD

**Issue by BenedicteNW** [cceh/c-salt_vedaweb_sources#5]
Griffith's translations reads: 

"The waters, they received that germ primeval wherein the Gods were gathefed all together."

gathefed → gathered

**Comment by bkis** [comment]
Thank you for your help. We included your suggestions into our recent data corrections. The updated data will be online via the VedaWeb platform as well as the [new data repository](https://github.com/VedaWebProject/vedaweb-data).
