### ISSUE TITLE
Iterative compounds in Aurfrecht

### ISSUE THREAD

**Issue by Yuzki** [cceh/c-salt_vedaweb_sources#7]
There is a discrepancy between the printed version and the electronic version. The printed version contains hyphens for iterative compounds, but this electronic version does not.
e.g.) 3.4.1: Samít-samit (printed/original) vs. samít samit (here); ṣucā́-ṣucā (printed) vs. śucā́ śucā (here). 
(Maybe not only in the verse, but also in other verses.)

**Comment by bkis** [comment]
Thank you for your help. We included your suggestions into our recent data corrections. The updated data will be online via the VedaWeb platform as well as the [new data repository](https://github.com/VedaWebProject/vedaweb-data).
